package com.client.jwt.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-26T11:24:24.453+05:30
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://in28minutes.com/students", name = "StudentPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StudentPort {

    @WebMethod(operationName = "GetStudentDetails")
    @WebResult(name = "GetStudentDetailsResponse", targetNamespace = "http://in28minutes.com/students", partName = "GetStudentDetailsResponse")
    public GetStudentDetailsResponse getStudentDetails(

        @WebParam(partName = "GetStudentDetailsRequest", name = "GetStudentDetailsRequest", targetNamespace = "http://in28minutes.com/students")
        GetStudentDetailsRequest getStudentDetailsRequest
    );
}
