package com.client.jwt.security;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-26T11:24:24.568+05:30
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "StudentPortService",
                  wsdlLocation = "file:/C:/Users/770695/Desktop/security/src/main/resources/wsdl/student.wsdl",
                  targetNamespace = "http://in28minutes.com/students")
public class StudentPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://in28minutes.com/students", "StudentPortService");
    public final static QName StudentPortSoap11 = new QName("http://in28minutes.com/students", "StudentPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/770695/Desktop/security/src/main/resources/wsdl/student.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/770695/Desktop/security/src/main/resources/wsdl/student.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentPort
     */
    @WebEndpoint(name = "StudentPortSoap11")
    public StudentPort getStudentPortSoap11() {
        return super.getPort(StudentPortSoap11, StudentPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentPort
     */
    @WebEndpoint(name = "StudentPortSoap11")
    public StudentPort getStudentPortSoap11(WebServiceFeature... features) {
        return super.getPort(StudentPortSoap11, StudentPort.class, features);
    }

}
